### ISSUE TITLE
training stops at epoch 600!

### ISSUE THREAD

**Issue by MustafaAlahmid** [BADBADBADBOY/pytorchOCR#12]
The train stops at the 600 epoch and gives me this error
as I understand the model cannot find the image so it read it as none type
in the config file 
what does (test_gt_path) means ? 

raceback (most recent call last):
  File "tools/det_train.py", line 307, in <module>
    TrainValProgram(args)
  File "tools/det_train.py", line 255, in TrainValProgram
    rescall,precision,hmean = ModelEval(test_dataset, test_data_loader, model, img_process, checkpoints,config)
  File "tools/det_train.py", line 107, in ModelEval
    for batch_idx, (imgs, ori_imgs) in enumerate(test_data_loader):
  File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./ptocr/dataloader/DetLoad/DBProcess.py", line 120, in __getitem__
    img = resize_image(ori_img,self.config['base']['algorithm'], self.test_size,stride = self.config['testload']['stride'])
  File "./ptocr/utils/util_function.py", line 55, in resize_image
    height, width, _ = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by BADBADBADBOY** [comment]
> The train stops at the 600 epoch and gives me this error
> as I understand the model cannot find the image so it read it as none type
> in the config file
> what does (test_gt_path) means ?
> 
> raceback (most recent call last):
> File "tools/det_train.py", line 307, in 
> TrainValProgram(args)
> File "tools/det_train.py", line 255, in TrainValProgram
> rescall,precision,hmean = ModelEval(test_dataset, test_data_loader, model, img_process, checkpoints,config)
> File "tools/det_train.py", line 107, in ModelEval
> for batch_idx, (imgs, ori_imgs) in enumerate(test_data_loader):
> File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> data = self._next_data()
> File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
> return self._process_data(data)
> File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> data.reraise()
> File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
> raise self.exc_type(msg)
> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in 
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "./ptocr/dataloader/DetLoad/DBProcess.py", line 120, in **getitem**
> img = resize_image(ori_img,self.config['base']['algorithm'], self.test_size,stride = self.config['testload']['stride'])
> File "./ptocr/utils/util_function.py", line 55, in resize_image
> height, width, _ = img.shape
> AttributeError: 'NoneType' object has no attribute 'shape'

This is for verification, which is based on icdar2015 data set. If you don't have a verification set or don't want to do verification, you can set start_val greater than n_epoch in yaml file

**Comment by MustafaAlahmid** [comment]
> > The train stops at the 600 epoch and gives me this error
> > as I understand the model cannot find the image so it read it as none type
> > in the config file
> > what does (test_gt_path) means ?
> > raceback (most recent call last):
> > File "tools/det_train.py", line 307, in
> > TrainValProgram(args)
> > File "tools/det_train.py", line 255, in TrainValProgram
> > rescall,precision,hmean = ModelEval(test_dataset, test_data_loader, model, img_process, checkpoints,config)
> > File "tools/det_train.py", line 107, in ModelEval
> > for batch_idx, (imgs, ori_imgs) in enumerate(test_data_loader):
> > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> > data = self._next_data()
> > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
> > return self._process_data(data)
> > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> > data.reraise()
> > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
> > raise self.exc_type(msg)
> > AttributeError: Caught AttributeError in DataLoader worker process 0.
> > Original Traceback (most recent call last):
> > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> > data = fetcher.fetch(index)
> > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "./ptocr/dataloader/DetLoad/DBProcess.py", line 120, in **getitem**
> > img = resize_image(ori_img,self.config['base']['algorithm'], self.test_size,stride = self.config['testload']['stride'])
> > File "./ptocr/utils/util_function.py", line 55, in resize_image
> > height, width, _ = img.shape
> > AttributeError: 'NoneType' object has no attribute 'shape'
> 
> This is for verification, which is based on icdar2015 data set. If you don't have a verification set or don't want to do verification, you can set start_val greater than n_epoch in yaml file

thanks, I have tried this but I got same error 

I think the error beacuse of these:
 
test_gt_path and test_size
test_gt_path is the labels right ? 
test_size is number of test images ?

**Comment by BADBADBADBOY** [comment]
> > > The train stops at the 600 epoch and gives me this error
> > > as I understand the model cannot find the image so it read it as none type
> > > in the config file
> > > what does (test_gt_path) means ?
> > > raceback (most recent call last):
> > > File "tools/det_train.py", line 307, in
> > > TrainValProgram(args)
> > > File "tools/det_train.py", line 255, in TrainValProgram
> > > rescall,precision,hmean = ModelEval(test_dataset, test_data_loader, model, img_process, checkpoints,config)
> > > File "tools/det_train.py", line 107, in ModelEval
> > > for batch_idx, (imgs, ori_imgs) in enumerate(test_data_loader):
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> > > data = self._next_data()
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
> > > return self._process_data(data)
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> > > data.reraise()
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
> > > raise self.exc_type(msg)
> > > AttributeError: Caught AttributeError in DataLoader worker process 0.
> > > Original Traceback (most recent call last):
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> > > data = fetcher.fetch(index)
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > File "./ptocr/dataloader/DetLoad/DBProcess.py", line 120, in **getitem**
> > > img = resize_image(ori_img,self.config['base']['algorithm'], self.test_size,stride = self.config['testload']['stride'])
> > > File "./ptocr/utils/util_function.py", line 55, in resize_image
> > > height, width, _ = img.shape
> > > AttributeError: 'NoneType' object has no attribute 'shape'
> > 
> > 
> > This is for verification, which is based on icdar2015 data set. If you don't have a verification set or don't want to do verification, you can set start_val greater than n_epoch in yaml file
> 
> thanks, I have tried this but I got same error
> 
> I think the error beacuse of these:
> 
> test_gt_path and test_size
> test_gt_path is the labels right ?
> test_size is number of test images ?

If you set start_val greater than n_epoch, it will not be verified. If it will be verified, you need to debug to see what is causing it. On line 250 of https://github.com/badbadbadboy/pytorchocr/blob/master/tools/det _ train.py,
 test_gt_path refers to the address of the txt file of the  verification set label, and test_size refers to the length of the shortest edge when the picture is resize during verification

**Comment by BADBADBADBOY** [comment]
> > > The train stops at the 600 epoch and gives me this error
> > > as I understand the model cannot find the image so it read it as none type
> > > in the config file
> > > what does (test_gt_path) means ?
> > > raceback (most recent call last):
> > > File "tools/det_train.py", line 307, in
> > > TrainValProgram(args)
> > > File "tools/det_train.py", line 255, in TrainValProgram
> > > rescall,precision,hmean = ModelEval(test_dataset, test_data_loader, model, img_process, checkpoints,config)
> > > File "tools/det_train.py", line 107, in ModelEval
> > > for batch_idx, (imgs, ori_imgs) in enumerate(test_data_loader):
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> > > data = self._next_data()
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
> > > return self._process_data(data)
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> > > data.reraise()
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
> > > raise self.exc_type(msg)
> > > AttributeError: Caught AttributeError in DataLoader worker process 0.
> > > Original Traceback (most recent call last):
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> > > data = fetcher.fetch(index)
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > File "/home/nizarmassouh/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > File "./ptocr/dataloader/DetLoad/DBProcess.py", line 120, in **getitem**
> > > img = resize_image(ori_img,self.config['base']['algorithm'], self.test_size,stride = self.config['testload']['stride'])
> > > File "./ptocr/utils/util_function.py", line 55, in resize_image
> > > height, width, _ = img.shape
> > > AttributeError: 'NoneType' object has no attribute 'shape'
> > 
> > 
> > This is for verification, which is based on icdar2015 data set. If you don't have a verification set or don't want to do verification, you can set start_val greater than n_epoch in yaml file
> 
> thanks, I have tried this but I got same error
> 
> I think the error beacuse of these:
> 
> test_gt_path and test_size
> test_gt_path is the labels right ?
> test_size is number of test images ?

If you set start_val greater than n_epoch, it will not be verified. If it will be verified, you need to debug to see what is causing it. On line 250 of https://github.com/badbadbadboy/pytorchocr/blob/master/tools/det _train.py,
 test_gt_path refers to the address of the txt file of the  verification set label, and test_size refers to the length of the shortest edge when the picture is resize during verification

**Comment by MustafaAlahmid** [comment]
Thanks, solved as you said.
