### ISSUE TITLE
Cannot search your wechat number

### ISSUE THREAD

**Issue by ZhangQihan** [BADBADBADBOY/pytorchOCR#13]
fangxuwei:

hello.
thanks for your great work~ I want to add your wechat, but it prompts that cannot search this wechat number. is fxwfzsxyq correct ?

**Comment by fxwfzsxyq** [comment]
> fangxuwei:
> 
> hello.
> thanks for your great work~ I want to add your wechat, but it prompts that cannot search this wechat number. is fxwfzsxyq correct ?

I changed my WeChat number recently，it is -fxwispig-

**Comment by ZhangQihan** [comment]
> I changed my WeChat number recently，it is -fxwispig-
thx so much!
