### ISSUE TITLE
error: ‘connectedComponents’ was not declared in this scope

### ISSUE THREAD

**Issue by GeneralJing** [BADBADBADBOY/pytorchOCR#14]
pixelmerge.cpp:42:86: error: ‘connectedComponents’ was not declared in this scope
int label_num = connectedComponents(kernals[kernals.size() - 1], label_mat, 4);

**Comment by fxwfzsxyq** [comment]
> error: ‘connectedComponents’ was not declared in this scope

这个应该是你的opencv安装有问题

**Comment by GeneralJing** [comment]
嗯 我可以在Linux下正常查看OpenCV版本及库，怎么更改配置？我配置到我系统的应该也可以吧

**Comment by fxwfzsxyq** [comment]
> 嗯 我可以在Linux下正常查看OpenCV版本及库，怎么更改配置？我配置到我系统的应该也可以吧

需要配置opencv>3.0,建议使用docker，直接拉一个环境

**Comment by GeneralJing** [comment]
难怪了，我的版本是2.4.13，我的路径是-I/usr/local/include/opencv -I/usr/local/include，有docker镜像吗 没看到链接呢

**Comment by GeneralJing** [comment]
大佬，你的微信号是不是写错了？搜不到你

**Comment by fxwfzsxyq** [comment]
> 大佬，你的微信号是不是写错了？搜不到你

可以去docker hub上搜一个就行了，微信：-fxwispig-
