### ISSUE TITLE
DB的蒸馏dice_loss 跟 mse_loss的差别

### ISSUE THREAD

**Issue by zihao-lu** [BADBADBADBOY/pytorchOCR#15]
你好，请教个问题，我发现蒸馏用dice_loss的话loss很大，因为正负样本对loss值的贡献程度不一样，负样本的损失值会大很多，请问dice_loss 跟mse_loss对结果的影响有什么区别，多谢

**Comment by BADBADBADBOY** [comment]
> 你好，请教个问题，我发现蒸馏用dice_loss的话loss很大，因为正负样本对loss值的贡献程度不一样，负样本的损失值会大很多，请问dice_loss 跟mse_loss对结果的影响有什么区别，多谢

dice 的效果更好一些，这里蒸馏只是加入了大模型的预测作为soft label, 可用的loss就几个，也就实验一下而已
