### ISSUE TITLE
采用mobilenetv3速度反而变慢了，想问下是什么原因？

### ISSUE THREAD

**Issue by lifei1229** [BADBADBADBOY/pytorchOCR#18]
大佬大佬你好，我训练了 resnet18和mobilenetv3两个模型，转成onnx后 在cpu上mobilenetv3反而慢了特别多，请问是什么原因导致的?

**Comment by fxwfzsxyq** [comment]
不转onnx之前有测试过各自的时间吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 上午10:19
收件人: "BADBADBADBOY/pytorchOCR"<pytorchOCR@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [BADBADBADBOY/pytorchOCR] 采用mobilenetv3速度反而变慢了，想问下是什么原因？ (#18)





 
大佬大佬你好，我训练了 resnet18和mobilenetv3两个模型，转成onnx后 在cpu上mobilenetv3反而慢了特别多，请问是什么原因导致的?

**Comment by lifei1229** [comment]
> 不转onnx之前有测试过各自的时间吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年1月25日(星期一) 上午10:19 收件人: "BADBADBADBOY/pytorchOCR"<pytorchOCR@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [BADBADBADBOY/pytorchOCR] 采用mobilenetv3速度反而变慢了，想问下是什么原因？ (#18) 大佬大佬你好，我训练了 resnet18和mobilenetv3两个模型，转成onnx后 在cpu上mobilenetv3反而慢了特别多，请问是什么原因导致的? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

刚刚测试了下，不转onnx，在pytorch上 resnet18是66ms/张， mobilenetv3是 75ms/张

**Comment by fxwfzsxyq** [comment]
> > 不转onnx之前有测试过各自的时间吗
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "notifications"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2021年1月25日(星期一) 上午10:19 收件人: "BADBADBADBOY/pytorchOCR"<[pytorchOCR@noreply.github.com](mailto:pytorchOCR@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [BADBADBADBOY/pytorchOCR] 采用mobilenetv3速度反而变慢了，想问下是什么原因？ (#18) 大佬大佬你好，我训练了 resnet18和mobilenetv3两个模型，转成onnx后 在cpu上mobilenetv3反而慢了特别多，请问是什么原因导致的? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 刚刚测试了下，不转onnx，在pytorch上 resnet18是66ms/张， mobilenetv3是 75ms/张

我测试了一下，mobilev3的分类和resnet18的分类，确实resnet18的在cpu要快一些

**Comment by fxwfzsxyq** [comment]
> > 不转onnx之前有测试过各自的时间吗
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "notifications"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2021年1月25日(星期一) 上午10:19 收件人: "BADBADBADBOY/pytorchOCR"<[pytorchOCR@noreply.github.com](mailto:pytorchOCR@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [BADBADBADBOY/pytorchOCR] 采用mobilenetv3速度反而变慢了，想问下是什么原因？ (#18) 大佬大佬你好，我训练了 resnet18和mobilenetv3两个模型，转成onnx后 在cpu上mobilenetv3反而慢了特别多，请问是什么原因导致的? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 刚刚测试了下，不转onnx，在pytorch上 resnet18是66ms/张， mobilenetv3是 75ms/张

我单独测试了一下，确实mobilev3慢一些，我觉得是虽然他参数量小，但是多了hswish，hsigmoid拖慢了他的计算

**Comment by fxwfzsxyq** [comment]
> > > 不转onnx之前有测试过各自的时间吗
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "notifications"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2021年1月25日(星期一) 上午10:19 收件人: "BADBADBADBOY/pytorchOCR"<[pytorchOCR@noreply.github.com](mailto:pytorchOCR@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [BADBADBADBOY/pytorchOCR] 采用mobilenetv3速度反而变慢了，想问下是什么原因？ (#18) 大佬大佬你好，我训练了 resnet18和mobilenetv3两个模型，转成onnx后 在cpu上mobilenetv3反而慢了特别多，请问是什么原因导致的? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 刚刚测试了下，不转onnx，在pytorch上 resnet18是66ms/张， mobilenetv3是 75ms/张
> 
> 我单独测试了一下，确实mobilev3慢一些，我觉得是虽然他参数量小，但是多了hswish，hsigmoid拖慢了他的计算

我又测试了一下，单张测试的时候还是mobilev3快，但是一旦batch不断变大 , mobilev3会比resnet18慢，而且越大的batch越慢

**Comment by fxwfzsxyq** [comment]
> > > > 不转onnx之前有测试过各自的时间吗
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: "notifications"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2021年1月25日(星期一) 上午10:19 收件人: "BADBADBADBOY/pytorchOCR"<[pytorchOCR@noreply.github.com](mailto:pytorchOCR@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [BADBADBADBOY/pytorchOCR] 采用mobilenetv3速度反而变慢了，想问下是什么原因？ (#18) 大佬大佬你好，我训练了 resnet18和mobilenetv3两个模型，转成onnx后 在cpu上mobilenetv3反而慢了特别多，请问是什么原因导致的? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 刚刚测试了下，不转onnx，在pytorch上 resnet18是66ms/张， mobilenetv3是 75ms/张
> > 
> > 
> > 我单独测试了一下，确实mobilev3慢一些，我觉得是虽然他参数量小，但是多了hswish，hsigmoid拖慢了他的计算
> 
> 我又测试了一下，单张测试的时候还是mobilev3快，但是一旦batch不断变大 , mobilev3会比resnet18慢，而且越大的batch越慢

单张的时候图片比较小（640*640）的时候mobilev3快，但是当图片变大（1280*1280）的时候，mobilev3又比resnet18慢了
