### ISSUE TITLE
编译环境具体的配置是什么？

### ISSUE THREAD

**Issue by lzmisscc** [BADBADBADBOY/pytorchOCR#19]

**Comment by fxwfzsxyq** [comment]
> _No description provided._

首先只支持linux，编译需要安装有c++版本的opencv 3.0及以上，其他的就深度学习通用的环境应该ok。

**Comment by fxwfzsxyq** [comment]
> _No description provided._

还有看看这里是否对你有帮助 https://github.com/BADBADBADBOY/pytorchOCR/issues/16

**Comment by lzmisscc** [comment]
GCC > 6
C++版Opencv > 3 
可以成功编译。


> > _No description provided._
> 
> 编译有问题建议贴报错， 还有看看这里是否对你有帮助 #16

**Comment by wayne2tech** [comment]
![image](https://user-images.githubusercontent.com/56107092/137475018-d60910db-ee38-4c6e-bd08-b2d35c0c8091.png)
大佬，我这里也有C++版本的opencv，为何还是报错呢
