### ISSUE TITLE
w

### ISSUE THREAD

**Issue by johnnylili** [BADBADBADBOY/pytorchOCR#2]
谢谢您提供的预训练权重。想请问一下，db_resnet50_3x3在训练时是否有先在synthtext数据集上预训练，是否有使用deformable卷积。测试时short_side是736还是1152，thresh和box_thresh分别设置为多少？

**Comment by johnnylili** [comment]
谢谢您提供的预训练权重。想请问一下，db_resnet50_3x3在训练时是否有先在synthtext数据集上预训练，是否有使用deformable卷积。测试时short_side是736还是1152，thresh和box_thresh分别设置为多少？

**Comment by johnnylili** [comment]
> _No description provided._

**Comment by johnnylili** [comment]
谢谢您提供的预训练权重。想请问一下，db_resnet50_3x3在训练时是否有先在synthtext数据集上预训练，是否有使用deformable卷积。测试时short_side是736还是1152，thresh和box_thresh分别设置为多少？

**Comment by fxwfzsxyq** [comment]
> 谢谢您提供的预训练权重。想请问一下，db_resnet50_3x3在训练时是否有先在synthtext数据集上预训练，是否有使用deformable卷积。测试时short_side是736还是1152，thresh和box_thresh分别设置为多少？
db_resnet50_3x3是imagenet上的预训练模型，没有在synthtext训练过，3*3只是用3个3*3的卷积代替了原本的7*7，没有使用deformable卷积，这里测试都是用的论文中的测试标准，db用的736，0.5 , 0.6，具体在config里面有各个算法的测试配置，可以看里面的参数配置

**Comment by fxwfzsxyq** [comment]
> 谢谢您提供的预训练权重。想请问一下，db_resnet50_3x3在训练时是否有先在synthtext数据集上预训练，是否有使用deformable卷积。测试时short_side是736还是1152，thresh和box_thresh分别设置为多少？
db_resnet50_3x3是imagenet上的预训练模型，没有在synthtext训练过，33只是用3个33的卷积代替了原本的7*7，没有使用deformable卷积，这里测试都是用的论文中的测试标准，db用的736，0.5 , 0.6，具体在config里面有各个算法的测试配置，可以看里面的参数配置

**Comment by johnnylili** [comment]
> > 谢谢您提供的预训练权重。想请问一下，db_resnet50_3x3在训练时是否有先在synthtext数据集上预训练，是否有使用deformable卷积。测试时short_side是736还是1152，thresh和box_thresh分别设置为多少？
> > db_resnet50_3x3是imagenet上的预训练模型，没有在synthtext训练过，33只是用3个33的卷积代替了原本的7*7，没有使用deformable卷积，这里测试都是用的论文中的测试标准，db用的736，0.5 , 0.6，具体在config里面有各个算法的测试配置，可以看里面的参数配置

你好，我这边测试时出现了问题，能留个vx，方便我请教您吗？

**Comment by BADBADBADBOY** [comment]
> > > 谢谢您提供的预训练权重。想请问一下，db_resnet50_3x3在训练时是否有先在synthtext数据集上预训练，是否有使用deformable卷积。测试时short_side是736还是1152，thresh和box_thresh分别设置为多少？
> > > db_resnet50_3x3是imagenet上的预训练模型，没有在synthtext训练过，33只是用3个33的卷积代替了原本的7*7，没有使用deformable卷积，这里测试都是用的论文中的测试标准，db用的736，0.5 , 0.6，具体在config里面有各个算法的测试配置，可以看里面的参数配置
> 
> 你好，我这边测试时出现了问题，能留个vx，方便我请教您吗？
微信：fxwfzsxyq
