### ISSUE TITLE
Can't use Baidu cloud

### ISSUE THREAD

**Issue by aditya-jindal-trysolvio** [BADBADBADBOY/pytorchOCR#20]
Hey i am trying to use the sast_resnet50 model and it requires me to download the pretrained model from baidu cloud. But i can't download from baidu. Can u upload the model to gdrive.

**Comment by fxwfzsxyq** [comment]
> Hey i am trying to use the sast_resnet50 model and it requires me to download the pretrained model from baidu cloud. But i can't download from baidu. Can u upload the model to gdrive.

Sorry, I can't get over the wall right now, so I can't upload the model to the gdrive.

**Comment by fxwfzsxyq** [comment]
> > Hey i am trying to use the sast_resnet50 model and it requires me to download the pretrained model from baidu cloud. But i can't download from baidu. Can u upload the model to gdrive.
> 
> Sorry, I can't get over the wall right now, so I can't upload the model to the gdrive.

Here the Sast pre-training model is the provided by torchvision
