### ISSUE TITLE
Problem in det_train.py

### ISSUE THREAD

**Issue by aditya-jindal-trysolvio** [BADBADBADBOY/pytorchOCR#21]
Hey i was trying to train a Sast_resnet50 model. I find that the config parameters in the config file are overwritten by the default parameters set in the det_train.py file for some parameters like n_epoch, start_val etc 
https://github.com/BADBADBADBOY/pytorchOCR/blob/049a4b3f3d9502eb3fc8917c8353edeceb3c9d65/tools/det_train.py#L300-L302
because of the following line:
https://github.com/BADBADBADBOY/pytorchOCR/blob/049a4b3f3d9502eb3fc8917c8353edeceb3c9d65/tools/det_train.py#L151
Can u fix this please.

**Comment by fxwfzsxyq** [comment]
> Hey i was trying to train a Sast_resnet50 model. I find that the config parameters in the config file are overwritten by the default parameters set in the det_train.py file for some parameters like n_epoch, start_val etc
> https://github.com/BADBADBADBOY/pytorchOCR/blob/049a4b3f3d9502eb3fc8917c8353edeceb3c9d65/tools/det_train.py#L300-L302
> 
> 
> because of the following line:
> https://github.com/BADBADBADBOY/pytorchOCR/blob/049a4b3f3d9502eb3fc8917c8353edeceb3c9d65/tools/det_train.py#L151
> 
> 
> Can u fix this please.
you should use this training command ，for example，python3 tools/det_train.py --config ./config/det_DB_mobilev3.yaml --log_str train_log  --n_epoch 1200 --start_val 600 --base_lr 0.002 --gpu_id 2

**Comment by fxwfzsxyq** [comment]
> > Hey i was trying to train a Sast_resnet50 model. I find that the config parameters in the config file are overwritten by the default parameters set in the det_train.py file for some parameters like n_epoch, start_val etc
> > https://github.com/BADBADBADBOY/pytorchOCR/blob/049a4b3f3d9502eb3fc8917c8353edeceb3c9d65/tools/det_train.py#L300-L302
> > 
> > because of the following line:
> > https://github.com/BADBADBADBOY/pytorchOCR/blob/049a4b3f3d9502eb3fc8917c8353edeceb3c9d65/tools/det_train.py#L151
> > 
> > Can u fix this please.
> 
> you should use this training command ，for example，python3 tools/det_train.py --config ./config/det_DB_mobilev3.yaml --log_str train_log --n_epoch 1200 --start_val 600 --base_lr 0.002 --gpu_id 2

For training SAST, I recommend using det_sast.py instead of det_train.py
