### ISSUE TITLE
multiple classes

### ISSUE THREAD

**Issue by aditya-jindal-trysolvio** [BADBADBADBOY/pytorchOCR#27]
will it be possible to have multiple classes. I want to detect text, equations, tables, graphs in a document. Will it be possible to do it with this model.

**Comment by BADBADBADBOY** [comment]
> will it be possible to have multiple classes. I want to detect text, equations, tables, graphs in a document. Will it be possible to do it with this model.

I think it's feasible. You can try to change the loss of classification to multi classification. Some people changed the loss to multi classification before, and used dbnet to do text detection in different languages
