### ISSUE TITLE
Error while using pretrained checkpoint

### ISSUE THREAD

**Issue by hailcpy** [BADBADBADBOY/pytorchOCR#28]
Error:
```
Traceback (most recent call last):
  File "./tools/det_infer.py", line 193, in <module>
    InferImage(config)
  File "./tools/det_infer.py", line 152, in InferImage
    test_bin = TestProgram(config)
  File "./tools/det_infer.py", line 85, in __init__
    model = load_model(model,config['infer']['model_path'])
  File "./ptocr/utils/util_function.py", line 145, in load_model
    model_dict = torch.load(model_path)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xfd'.
```
I am using the checkpoint in `ag_SAST_bb_resnet50_he_SASTHead_bs_8_ep_900` and the config file `det_SAST_resnet50.yaml`.

**Comment by BADBADBADBOY** [comment]
> Error:
> 
> ```
> Traceback (most recent call last):
>   File "./tools/det_infer.py", line 193, in <module>
>     InferImage(config)
>   File "./tools/det_infer.py", line 152, in InferImage
>     test_bin = TestProgram(config)
>   File "./tools/det_infer.py", line 85, in __init__
>     model = load_model(model,config['infer']['model_path'])
>   File "./ptocr/utils/util_function.py", line 145, in load_model
>     model_dict = torch.load(model_path)
>   File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, '\xfd'.
> ```
> 
> I am using the checkpoint in `ag_SAST_bb_resnet50_he_SASTHead_bs_8_ep_900` and the config file `det_SAST_resnet50.yaml`.

Is your torch version the same as mine

**Comment by hailcpy** [comment]
Thanks, it worked with `torch == 1.4.0`. Is there any particular version requirement of python, etc while running `sh make.sh`. I am having following problem in using DBnet after `sh make.sh` ran successfully.
config used `det_DB_resnet50.yaml`
`ImportError: ./ptocr/postprocess/dbprocess/cppdbprocess.so: undefined symbol: _ZN2cv9boxPointsENS_11RotatedRectERKNS_12_OutputArrayE`

**Comment by fxwfzsxyq** [comment]
> Thanks, it worked with `torch == 1.4.0`. Is there any particular version requirement of python, etc while running `sh make.sh`. I am having following problem in using DBnet after `sh make.sh` ran successfully.
> config used `det_DB_resnet50.yaml`
> `ImportError: ./ptocr/postprocess/dbprocess/cppdbprocess.so: undefined symbol: _ZN2cv9boxPointsENS_11RotatedRectERKNS_12_OutputArrayE`

It seems to be a problem with OpenCV. The C + + version of OpenCV 3.0 or above is required for compilation

**Comment by aditya-jindal-trysolvio** [comment]
I tried with c++ OpenCV version greater than 3 and still same error. I got some warnings while running `sh infer.sh`. Here is the output while running `sh infer.sh`.
```
rm -rf adaptor.so
g++ -o adaptor.so -I include  -std=c++11 -O3 -I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-1chSKv/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions adaptor.cpp include/clipper/clipper.cpp --shared -fPIC
In file included from include/pybind11/pytypes.h:12:0,
                 from include/pybind11/cast.h:13,
                 from include/pybind11/attr.h:13,
                 from include/pybind11/pybind11.h:43,
                 from adaptor.cpp:1:
adaptor.cpp: In function ‘PyObject* PyInit_adaptor()’:
include/pybind11/common.h:232:34: warning: ‘PyObject* pybind11_init()’ is deprecated: PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE [-Wdeprecated-declarations]
             return pybind11_init();                                            \
                                  ^
adaptor.cpp:53:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^~~~~~~~~~~~~~~
include/pybind11/common.h:217:22: note: declared here
     static PyObject *pybind11_init();                                          \
                      ^
adaptor.cpp:53:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^~~~~~~~~~~~~~~
include/clipper/clipper.cpp: In member function ‘void ClipperLib::Clipper::FixupFirstLefts3(ClipperLib::OutRec*, ClipperLib::OutRec*)’:
include/clipper/clipper.cpp:3665:13: warning: unused variable ‘firstLeft’ [-Wunused-variable]
     OutRec* firstLeft = ParseFirstLeft(outRec->FirstLeft);
             ^~~~~~~~~
rm -rf pixelmerge.so
g++ -o pixelmerge.so -I include -I/usr/local/include/opencv4/ -std=c++11 -O3 -I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-1chSKv/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall  pixelmerge.cpp include/clipper/clipper.cpp --shared -fPIC ``
include/clipper/clipper.cpp: In member function ‘void ClipperLib::Clipper::FixupFirstLefts3(ClipperLib::OutRec*, ClipperLib::OutRec*)’:
include/clipper/clipper.cpp:3665:13: warning: unused variable ‘firstLeft’ [-Wunused-variable]
     OutRec* firstLeft = ParseFirstLeft(outRec->FirstLeft);
             ^~~~~~~~~
rm -rf cppdbprocess.so
g++ -o cppdbprocess.so -I include -I/usr/local/include/opencv4/ -std=c++11 -O3 -I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-1chSKv/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall  cppdbprocess.cpp include/clipper/clipper.cpp --shared -fPIC ``
cppdbprocess.cpp: In member function ‘cv::RotatedRect cppdbprocess::PostProcessor::UnClip(std::vector<std::vector<float> >, const float&)’:
cppdbprocess.cpp:70:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int j = 0; j < soln.size(); j++) {
                   ~~^~~~~~~~~~~~~
cppdbprocess.cpp:71:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < soln[soln.size() - 1].size(); i++) {
                     ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cppdbprocess.cpp: In member function ‘std::vector<std::vector<std::vector<int> > > cppdbprocess::PostProcessor::FilterTagDetRes(std::vector<std::vector<std::vector<int> > >, float, float, cv::Mat)’:
cppdbprocess.cpp:340:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int n = 0; n < boxes.size(); n++) {
                   ~~^~~~~~~~~~~~~~
cppdbprocess.cpp:342:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int m = 0; m < boxes[0].size(); m++) {
                     ~~^~~~~~~~~~~~~~~~~
cppdbprocess.cpp:351:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int n = 0; n < boxes.size(); n++) {
                   ~~^~~~~~~~~~~~~~
include/clipper/clipper.cpp: In member function ‘void ClipperLib::Clipper::FixupFirstLefts3(ClipperLib::OutRec*, ClipperLib::OutRec*)’:
include/clipper/clipper.cpp:3665:13: warning: unused variable ‘firstLeft’ [-Wunused-variable]
     OutRec* firstLeft = ParseFirstLeft(outRec->FirstLeft);

```

**Comment by hailcpy** [comment]
I tried with c++ OpenCV version greater than 3 and still same error. I got some warnings while running `sh infer.sh`. Here is the output while running `sh infer.sh`.
```
rm -rf adaptor.so
g++ -o adaptor.so -I include  -std=c++11 -O3 -I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-1chSKv/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions adaptor.cpp include/clipper/clipper.cpp --shared -fPIC
In file included from include/pybind11/pytypes.h:12:0,
                 from include/pybind11/cast.h:13,
                 from include/pybind11/attr.h:13,
                 from include/pybind11/pybind11.h:43,
                 from adaptor.cpp:1:
adaptor.cpp: In function ‘PyObject* PyInit_adaptor()’:
include/pybind11/common.h:232:34: warning: ‘PyObject* pybind11_init()’ is deprecated: PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE [-Wdeprecated-declarations]
             return pybind11_init();                                            \
                                  ^
adaptor.cpp:53:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^~~~~~~~~~~~~~~
include/pybind11/common.h:217:22: note: declared here
     static PyObject *pybind11_init();                                          \
                      ^
adaptor.cpp:53:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^~~~~~~~~~~~~~~
include/clipper/clipper.cpp: In member function ‘void ClipperLib::Clipper::FixupFirstLefts3(ClipperLib::OutRec*, ClipperLib::OutRec*)’:
include/clipper/clipper.cpp:3665:13: warning: unused variable ‘firstLeft’ [-Wunused-variable]
     OutRec* firstLeft = ParseFirstLeft(outRec->FirstLeft);
             ^~~~~~~~~
rm -rf pixelmerge.so
g++ -o pixelmerge.so -I include -I/usr/local/include/opencv4/ -std=c++11 -O3 -I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-1chSKv/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall  pixelmerge.cpp include/clipper/clipper.cpp --shared -fPIC ``
include/clipper/clipper.cpp: In member function ‘void ClipperLib::Clipper::FixupFirstLefts3(ClipperLib::OutRec*, ClipperLib::OutRec*)’:
include/clipper/clipper.cpp:3665:13: warning: unused variable ‘firstLeft’ [-Wunused-variable]
     OutRec* firstLeft = ParseFirstLeft(outRec->FirstLeft);
             ^~~~~~~~~
rm -rf cppdbprocess.so
g++ -o cppdbprocess.so -I include -I/usr/local/include/opencv4/ -std=c++11 -O3 -I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-1chSKv/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall  cppdbprocess.cpp include/clipper/clipper.cpp --shared -fPIC ``
cppdbprocess.cpp: In member function ‘cv::RotatedRect cppdbprocess::PostProcessor::UnClip(std::vector<std::vector<float> >, const float&)’:
cppdbprocess.cpp:70:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int j = 0; j < soln.size(); j++) {
                   ~~^~~~~~~~~~~~~
cppdbprocess.cpp:71:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < soln[soln.size() - 1].size(); i++) {
                     ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cppdbprocess.cpp: In member function ‘std::vector<std::vector<std::vector<int> > > cppdbprocess::PostProcessor::FilterTagDetRes(std::vector<std::vector<std::vector<int> > >, float, float, cv::Mat)’:
cppdbprocess.cpp:340:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int n = 0; n < boxes.size(); n++) {
                   ~~^~~~~~~~~~~~~~
cppdbprocess.cpp:342:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int m = 0; m < boxes[0].size(); m++) {
                     ~~^~~~~~~~~~~~~~~~~
cppdbprocess.cpp:351:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int n = 0; n < boxes.size(); n++) {
                   ~~^~~~~~~~~~~~~~
include/clipper/clipper.cpp: In member function ‘void ClipperLib::Clipper::FixupFirstLefts3(ClipperLib::OutRec*, ClipperLib::OutRec*)’:
include/clipper/clipper.cpp:3665:13: warning: unused variable ‘firstLeft’ [-Wunused-variable]
     OutRec* firstLeft = ParseFirstLeft(outRec->FirstLeft);

```

**Comment by hailcpy** [comment]
Also while using the `SAST_resnet50` checkpoints, i got some nice predictions, but there are some places where the model is not detecting text. The model doesn't detect equations and that is ok since it wasn't trained on them but it doesn't detect text on many places where the paddleocr model was detecting it. What could be the reason? Is it because it was not trained on such data?
Output of SAST_resnet50
![AMU-Engineering-Entrance-Question-Papers-5](https://user-images.githubusercontent.com/60291306/110141988-b1e88100-7dfb-11eb-89d5-e57ccae00888.jpg)
![image](https://user-images.githubusercontent.com/60291306/110142329-0d1a7380-7dfc-11eb-9528-0a8836c274b6.png)
in the second image you can see it missed bbox on 'in'

**Comment by BADBADBADBOY** [comment]
> I tried with c++ OpenCV version greater than 3 and still same error. I got some warnings while running `sh infer.sh`. Here is the output while running `sh infer.sh`

The warning does not affect the operation, it should be fine, I am not sure what your problem is, my OpenCV version is 3.2. Is your OpenCV of C ++ consistent with the version of Python CV2? If you can run test of Sast, you should also be able to run DB. If not, you can change DB post-processing to Python instead of C ++

**Comment by BADBADBADBOY** [comment]
> Also while using the `SAST_resnet50` checkpoints, i got some nice predictions, but there are some places where the model is not detecting text. The model doesn't detect equations and that is ok since it wasn't trained on them but it doesn't detect text on many places where the paddleocr model was detecting it. What could be the reason? Is it because it was not trained on such data?
> Output of SAST_resnet50
> ![AMU-Engineering-Entrance-Question-Papers-5](https://user-images.githubusercontent.com/60291306/110141988-b1e88100-7dfb-11eb-89d5-e57ccae00888.jpg)
> ![image](https://user-images.githubusercontent.com/60291306/110142329-0d1a7380-7dfc-11eb-9528-0a8836c274b6.png)
> in the second image you can see it missed bbox on 'in'

First of all, is your paddleocr model also SAST? Secondly, my model is only trained on icdar2015 data set. Paddleocr uses multiple data sets, so the effect will be better. It is suggested that the effect should be seen after training specific data sets. Finally, I hope you can solve the problem of DB. I still suggest using dB. Paddleocr also uses dB for text detection,

**Comment by EricHuiK** [comment]
Not too familiar with Makefile for me,I modified it to cmake,this is fine to me
cmake_minimum_required(VERSION 3.5)

project(cppdbprocess)

set(CMAKE_CXX_STANDARD_REQUIRED OFF)
set(SRC_LIST ./cppdbprocess.cpp  ./include/clipper/clipper.cpp)
SET(CMAKE_BUILD_TYPE "Release")
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb")
else()
        set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -Ofast -Wfatal-errors -pthread -D_MWAITXINTRIN_H_INCLUDED")
endif()
add_library(cppdbprocess SHARED ${SRC_LIST})

include_directories(/prodataocr/3rdparty_opencv/linux/4.2.0/include)
set(python_lib /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.so)

set(opencv_lib
   /prodataocr/3rdparty_opencv/linux/4.2.0/lib/libopencv_highgui.so
   /prodataocr/3rdparty_opencv/linux/4.2.0/lib/libopencv_imgcodecs.so.4.2
   /prodataocr/3rdparty_opencv/linux/4.2.0/lib/libopencv_imgproc.so.4.2
   /prodataocr/3rdparty_opencv/linux/4.2.0/lib/libopencv_core.so
   )
target_link_libraries(cppdbprocess ${python_lib})
target_link_libraries(cppdbprocess ${opencv_lib})

#finally 
mv libcppdbprocess.so  cppdbprocess .so
