### ISSUE TITLE
换数据集 为什么loss 一直是 0 

### ISSUE THREAD

**Issue by myw8** [BADBADBADBOY/pytorchOCR#29]
换数据集 loss 一直是 0  数据输入 检查几次 没啥问题
![image](https://user-images.githubusercontent.com/17568519/110437288-2a975800-80f0-11eb-82bc-b15146a608d7.png)

**Comment by fxwfzsxyq** [comment]
> 换数据集 loss 一直是 0 数据输入 检查几次 没啥问题
> ![image](https://user-images.githubusercontent.com/17568519/110437288-2a975800-80f0-11eb-82bc-b15146a608d7.png)

确认下生成的label图是否有问题
