### ISSUE TITLE
请教如何进行模型蒸馏？

### ISSUE THREAD

**Issue by zwy4896** [BADBADBADBOY/pytorchOCR#3]
Hi，我看到readme里模型蒸馏这一块，经过teacher（resnet50）指导过的模型（mobilev3），性能都会得到不小的提升。我很好奇这个蒸馏是怎么做的，可否赐教？不胜感激

**Comment by fxwfzsxyq** [comment]
> Hi，我看到readme里模型蒸馏这一块，经过teacher（resnet50）指导过的模型（mobilev3），性能都会得到不小的提升。我很好奇这个蒸馏是怎么做的，可否赐教？不胜感激

https://github.com/BADBADBADBOY/pytorchOCR/blob/master/ptocr/utils/gen_teacher_model.py  其实也比较简单，就是用teacher model出来的结果来生成soft label和之前的label一起监督训练
