### ISSUE TITLE
蒸馏和剪枝的模型可以提供吗

### ISSUE THREAD

**Issue by lgcy** [BADBADBADBOY/pytorchOCR#30]
大佬可以分享一下列表里面蒸馏以及剪枝好的模型吗

**Comment by BADBADBADBOY** [comment]
> 大佬可以分享一下列表里面蒸馏以及剪枝好的模型吗

提供不了了，被我删了，建议可以自己训练，这个也不难，而且这个模型提供了也没啥用啊
