### ISSUE TITLE
ctw1500

### ISSUE THREAD

**Issue by seekingdeep** [BADBADBADBOY/pytorchOCR#35]
This repository is interesting,
though what are the results of the text detection methods (PAN, DBnet, PSEnet, ...) on the CTW1500 dataset
Recall, precision ..

**Comment by fxwfzsxyq** [comment]
> This repository is interesting,
> though what are the results of the text detection methods (PAN, DBnet, PSEnet, ...) on the CTW1500 dataset
> Recall, precision ..

Sorry, I have only trained and tested on the icdar2015 dataset

**Comment by seekingdeep** [comment]
ok
