### ISSUE TITLE
Paper 87.3% vs your implementation 83.44%

### ISSUE THREAD

**Issue by seekingdeep** [BADBADBADBOY/pytorchOCR#36]
The paper shows promising results of 87.3% F-measure on icdar2015, while your implementation scores ~ 83.5%
How to achieve similar results to the [main implementation](https://github.com/MhLiao/DB)?
what is the difference between your implementation and the main?

**Comment by fxwfzsxyq** [comment]
> The paper shows promising results of 87.3% F-measure on icdar2015, while your implementation scores ~ 83.5%
> How to achieve similar results to the [main implementation](https://github.com/MhLiao/DB)?
> what is the difference between your implementation and the main?

In order to improve the effect, the author used Deformable convolution in the backbone and pre-trained on the sythtext data set, but it did not do in this project

**Comment by seekingdeep** [comment]
ok
