### ISSUE TITLE
center_loss

### ISSUE THREAD

**Issue by lgcy** [BADBADBADBOY/pytorchOCR#39]
请问如果要使用center loss，应该用哪个文件进行训练

**Comment by BADBADBADBOY** [comment]
> 请问如果要使用center loss，应该用哪个文件进行训练

在master分支的rec_CRNN_resnet34_paddle.yaml可以用。新分支我去掉centerloss训练

**Comment by lgcy** [comment]
> > 请问如果要使用center loss，应该用哪个文件进行训练
> 
> 在master分支的rec_CRNN_resnet34_paddle.yaml可以用。新分支我去掉centerloss训练

新分支为什么去掉了，效果不好吗

**Comment by BADBADBADBOY** [comment]
> > > 请问如果要使用center loss，应该用哪个文件进行训练
> > 
> > 
> > 在master分支的rec_CRNN_resnet34_paddle.yaml可以用。新分支我去掉centerloss训练
> 
> 新分支为什么去掉了，效果不好吗
没仔细对比过，感觉提升不明显，省的麻烦就去掉了

**Comment by ReverseSystem001** [comment]
> > > 请问如果要使用center loss，应该用哪个文件进行训练
> > 
> > 
> > 在master分支的rec_CRNN_resnet34_paddle.yaml可以用。新分支我去掉centerloss训练
> 
> 新分支为什么去掉了，效果不好吗

哈喽，你做过对比没，我这边也发现效果不是很明显
