### ISSUE TITLE
Dbnet多语种文本检测数据集格式是什么样子的，class这个类别信息加在哪里呢

### ISSUE THREAD

**Issue by aishangmaxiaoming** [BADBADBADBOY/pytorchOCR#41]

**Comment by fxwfzsxyq** [comment]
> _No description provided._

x1,y1,x2,y2,x3,y3,x4,y4,class

类别从0开始

**Comment by aishangmaxiaoming** [comment]
> > _No description provided._
> 
> x1,y1,x2,y2,x3,y3,x4,y4,class
> 
> 类别从0开始

<img width="637" alt="image" src="https://user-images.githubusercontent.com/67897601/124431818-78248880-dda3-11eb-81d9-dee9667a76b8.png">
1. 如果有5类的话，numberclass 在哪里改呢，是5还是6呢？2. 另外 想问下大佬这个多类别的检测效果怎么样

**Comment by fxwfzsxyq** [comment]
> > > _No description provided._
> > 
> > 
> > x1,y1,x2,y2,x3,y3,x4,y4,class
> > 类别从0开始
> 
> <img alt="image" width="637" src="https://user-images.githubusercontent.com/67897601/124431818-78248880-dda3-11eb-81d9-dee9667a76b8.png">
> 
> 1. 如果有5类的话，numberclass 在哪里改呢，是5还是6呢？2. 另外 想问下大佬这个多类别的检测效果怎么样

https://github.com/BADBADBADBOY/pytorchOCR/blob/version2/config/det_DB_resnet50_mul.yaml 

改里面的n_class，5类的话就是5，我测试下来效果还可以吧，可能不同数据集不一样，有个兄弟用了感觉还不错

**Comment by aishangmaxiaoming** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > x1,y1,x2,y2,x3,y3,x4,y4,class
> > > 类别从0开始
> > 
> > 
> > <img alt="image" width="637" src="https://user-images.githubusercontent.com/67897601/124431818-78248880-dda3-11eb-81d9-dee9667a76b8.png">
> > 
> > 1. 如果有5类的话，numberclass 在哪里改呢，是5还是6呢？2. 另外 想问下大佬这个多类别的检测效果怎么样
> 
> https://github.com/BADBADBADBOY/pytorchOCR/blob/version2/config/det_DB_resnet50_mul.yaml
> 
> 改里面的n_class，5类的话就是5，我测试下来效果还可以吧，可能不同数据集不一样，有个兄弟用了感觉还不错

好的，谢谢大佬。我试一下
