### ISSUE TITLE
infer.sh在哪里呢

### ISSUE THREAD

**Issue by aishangmaxiaoming** [BADBADBADBOY/pytorchOCR#42]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/67897601/124535089-23871900-de48-11eb-9ba1-64a78b32e2e1.png">

**Comment by fxwfzsxyq** [comment]
在master分支有，但是你需要根据实际情况改一下，有些参数你是没有的

**Comment by aishangmaxiaoming** [comment]
> 在master分支有，但是你需要根据实际情况改一下，有些参数你是没有的
