### ISSUE TITLE
推理需要下载C++的opencv吗？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [BADBADBADBOY/pytorchOCR#43]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/67897601/124539601-61883b00-de50-11eb-929a-cf64d7023dfa.png"

**Comment by aishangmaxiaoming** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/67897601/124539665-7e247300-de50-11eb-8482-1f226f8e5f0d.png">

**Comment by aishangmaxiaoming** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/67897601/124539824-c2b00e80-de50-11eb-91ee-c0881c5c60d4.png">

**Comment by fxwfzsxyq** [comment]
把这个注释掉




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 中午11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] 推理需要下载C++的opencv吗？ (#43)

**Comment by aishangmaxiaoming** [comment]
> 把这个注释掉
> […](#)

<img width="595" alt="image" src="https://user-images.githubusercontent.com/67897601/124540100-51249000-de51-11eb-98ec-0697cafe8625.png">
注释掉from .cppdbprocess import db_cpp ，db_cpp就没定义啦，这怎么办呢

**Comment by fxwfzsxyq** [comment]
不是这里，下面，把这个换成Python的，注释掉c++的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 中午11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] 推理需要下载C++的opencv吗？ (#43)





  
把这个注释掉
 …
  

 注释掉from .cppdbprocess import db_cpp ，db_cpp就没定义啦，这怎么办呢

**Comment by fxwfzsxyq** [comment]
https://orangeai.bestpay.com.cn/aipaas-gateway/u0zzg7d02lupv152-notebook/edit/pytorchOCR_version2/ptocr/postprocess/DBpostprocess.py


在这里把12行注释掉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BADBADBADBOY/pytorchOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BADBADBADBOY/pytorchOCR] 推理需要下载C++的opencv吗？ (#43)





  
把这个注释掉
 …
  

 注释掉from .cppdbprocess import db_cpp ，db_cpp就没定义啦，这怎么办呢

**Comment by fxwfzsxyq** [comment]
你做多类别检测，你的yaml文件是不是搞错了，用这个https://github.com/BADBADBADBOY/pytorchOCR/blob/version2/config/det_DB_resnet50_mul.yaml

**Comment by aishangmaxiaoming** [comment]
> 你做多类别检测，你的yaml文件是不是搞错了，用这个https://github.com/BADBADBADBOY/pytorchOCR/blob/version2/config/det_DB_resnet50_mul.yaml

谢谢大佬，我先试试单一类别的能不能跑通，还有效果，哈哈
