### ISSUE TITLE
训练多类别时报错：    (new_polys.shape[0], polys.shape[1] // 2, 2)) IndexError: tuple index out of range

### ISSUE THREAD

**Issue by aishangmaxiaoming** [BADBADBADBOY/pytorchOCR#44]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/67897601/124555604-dddb4800-de69-11eb-8fe2-0470c151ea7c.png">

**Comment by fxwfzsxyq** [comment]
你的数据格式有问题吧

**Comment by aishangmaxiaoming** [comment]
> 你的数据格式有问题吧

<img width="678" alt="image" src="https://user-images.githubusercontent.com/67897601/124556283-afaa3800-de6a-11eb-8198-8cd5e6f4383d.png">
没问题呀

**Comment by fxwfzsxyq** [comment]
> > 你的数据格式有问题吧
> 
> <img alt="image" width="678" src="https://user-images.githubusercontent.com/67897601/124556283-afaa3800-de6a-11eb-8198-8cd5e6f4383d.png">
> 
> 没问题呀

你调试一下吧，肯定是数据的问题，有脏数据

**Comment by aishangmaxiaoming** [comment]
> > > 你的数据格式有问题吧
> > 
> > 
> > <img alt="image" width="678" src="https://user-images.githubusercontent.com/67897601/124556283-afaa3800-de6a-11eb-8198-8cd5e6f4383d.png">
> > 没问题呀
> 
> 你调试一下吧，肯定是数据的问题，有脏数据

好的，想问下，poly支持超过4点吗，比如弯曲文本poly不只四个，可以用这样的数据训练吗

**Comment by fxwfzsxyq** [comment]
目前不行，需要稍微改一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] 训练多类别时报错：    (new_polys.shape[0], polys.shape[1] // 2, 2)) IndexError: tuple index out of range (#44)





    
你的数据格式有问题吧
   没问题呀  
你调试一下吧，肯定是数据的问题，有脏数据
  
好的，想问下，poly支持超过4点吗，比如弯曲文本poly不只四个，可以用这样的数据训练吗
