### ISSUE TITLE
大佬，训练一个epoch,最后一个iter报错：RuntimeError: can't start new thread。

### ISSUE THREAD

**Issue by aishangmaxiaoming** [BADBADBADBOY/pytorchOCR#45]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/67897601/124591369-ccf0fd80-de8e-11eb-9614-c9c1a8a26bd1.png">

**Comment by fxwfzsxyq** [comment]
这个我也不知道 你百度下原因 可能是pytorch问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 晚上7:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[BADBADBADBOY/pytorchOCR] 大佬，训练一个epoch,最后一个iter报错：RuntimeError: can&#39;t start new thread。 (#45)

**Comment by aishangmaxiaoming** [comment]
> 这个我也不知道 你百度下原因 可能是pytorch问题------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年7月6日(星期二) 晚上7:18 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[BADBADBADBOY/pytorchOCR] 大佬，训练一个epoch,最后一个iter报错：RuntimeError: can&#39;t start new thread。 (#45)
好的
