### ISSUE TITLE
跑了1050个epoch，加载立刻预训练配置文件det_DB_mobilev3.yaml mobilev3 acc一直是0.5 数据是icdar2015

### ISSUE THREAD

**Issue by cqray1990** [BADBADBADBOY/pytorchOCR#49]
rescall: 0.0 precision 0 hmean 0
1.459199	0.062712	0.584564	0.247517	0.500000	0.496002	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.448682	0.061665	0.585743	0.246292	0.500000	0.495721	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.457282	0.062799	0.584752	0.244542	0.500000	0.496219	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.451594	0.061926	0.584343	0.247993	0.500000	0.495847	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.459978	0.062059	0.584883	0.254502	0.500000	0.496135	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.463593	0.062810	0.584999	0.250493	0.500000	0.496049	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.493469	0.064592	0.584955	0.262590	0.500000	0.495914	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.463380	0.063310	0.584535	0.245751	0.500000	0.495802	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.458623	0.062604	0.585377	0.247204	0.500000	0.496111	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.459385	0.062462	0.584988	0.249776	0.500000	0.496124	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.463168	0.063523	0.584972	0.242966	0.500000	0.495909	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.465711	0.062989	0.585267	0.250549	0.500000	0.496129	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.455198	0.062120	0.585751	0.248248	0.500000	0.495769	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.448042	0.061768	0.584926	0.245438	0.500000	0.496067	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.450591	0.061941	0.584231	0.246950	0.500000	0.496101	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	
1.458228	0.062193	0.585139	0.251160	0.500000	0.496013	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000

**Comment by lixiangMindSpore** [comment]
您好，请问问题解决了吗？我也遇到了和您一样的问题。
![image](https://user-images.githubusercontent.com/78945582/174920437-187b6720-f116-4a04-9cae-336cdf736c43.png)
