### ISSUE TITLE
后处理代码编译

### ISSUE THREAD

**Issue by VixeruntR** [BADBADBADBOY/pytorchOCR#51]
作者您好，请问./pytorchOCR/ptocr/postprocess/ 下的代码有python版的么？里面只有DBnet的后处理部分有python版的代码，其余的都没有，c++的代码我怎么都编译不成功。

**Comment by fxwfzsxyq** [comment]
> 作者您好，请问./pytorchOCR/ptocr/postprocess/ 下的代码有python版的么？里面只有DBnet的后处理部分有python版的代码，其余的都没有，c++的代码我怎么都编译不成功。

你可以去对应算法原作者的项目下去下python版本，但是Python版本的除了DB，其他的算法都很慢

**Comment by VixeruntR** [comment]
> > 作者您好，请问./pytorchOCR/ptocr/postprocess/ 下的代码有python版的么？里面只有DBnet的后处理部分有python版的代码，其余的都没有，c++的代码我怎么都编译不成功。
> 
> 你可以去对应算法原作者的项目下去下python版本，但是Python版本的除了DB，其他的算法都很慢

好，谢谢你~我去找找。
另外问一下是不是找到了对应代码之后，基本只需要替换一下对应的c++函数就可以了？

**Comment by fxwfzsxyq** [comment]
> > > 作者您好，请问./pytorchOCR/ptocr/postprocess/ 下的代码有python版的么？里面只有DBnet的后处理部分有python版的代码，其余的都没有，c++的代码我怎么都编译不成功。
> > 
> > 
> > 你可以去对应算法原作者的项目下去下python版本，但是Python版本的除了DB，其他的算法都很慢
> 
> 好，谢谢你~我去找找。
> 另外问一下是不是找到了对应代码之后，基本只需要替换一下对应的c++函数就可以了？

输入输出你自己对应一下
