### ISSUE TITLE
db检测可以增加裁剪code吗 需要裁剪送入到ocr识别

### ISSUE THREAD

**Issue by yufanxin** [BADBADBADBOY/pytorchOCR#54]

**Comment by fxwfzsxyq** [comment]
> _No description provided._


def cal_distance(coord1,coord2):
    return math.sqrt((coord1[0]-coord2[0])**2+(coord1[1]-coord2[1])**2)

def cal_width_height(bbox):
    width = cal_distance((bbox[0],bbox[1]),(bbox[2],bbox[3]))
    height = cal_distance((bbox[2],bbox[3]),(bbox[4],bbox[5]))
    return int(width),int(height)

def get_perspective_image(image,bbox):
    width,height = cal_width_height(bbox)
    pts1 = np.float32([[0,0],[width,0],[width,height],[0,height]])
    pts2 = np.float32(bbox.reshape(4,2))
    M = cv2.getPerspectiveTransform(pts2,pts1)
    dst = cv2.warpPerspective(image,M,(width,height))
    return dst

你可以用get_perspective_image函数，输入是原图和1*8的坐标，循环调用

**Comment by yufanxin** [comment]
> 
> 
> > _No description provided._
> 
> def cal_distance(coord1,coord2):
> return math.sqrt((coord1[0]-coord2[0])**2+(coord1[1]-coord2[1])**2)
> 
> def cal_width_height(bbox):
> width = cal_distance((bbox[0],bbox[1]),(bbox[2],bbox[3]))
> height = cal_distance((bbox[2],bbox[3]),(bbox[4],bbox[5]))
> return int(width),int(height)
> 
> def get_perspective_image(image,bbox):
> width,height = cal_width_height(bbox)
> pts1 = np.float32([[0,0],[width,0],[width,height],[0,height]])
> pts2 = np.float32(bbox.reshape(4,2))
> M = cv2.getPerspectiveTransform(pts2,pts1)
> dst = cv2.warpPerspective(image,M,(width,height))
> return dst
> 
> 你可以用get_perspective_image函数，输入是原图和1*8的坐标，循环调用

收到，谢谢
