### ISSUE TITLE
加载剪枝模型的推理的demo怎么没有呢

### ISSUE THREAD

**Issue by cqray1990** [BADBADBADBOY/pytorchOCR#58]

**Comment by fxwfzsxyq** [comment]
> _No description provided._
https://github.com/BADBADBADBOY/pytorchOCR/blob/version2/tools/det_train.py  这里只在训练的时候进行了finetune，测试效果，所以没有写infer的逻辑，213行有加载的逻辑，在infer里面自己改下调用下这个函数就行了
