### ISSUE TITLE
我发现mobilenet里的semodule没有对channel压缩，在forward函数里没有这一步。

### ISSUE THREAD

**Issue by DCC-lzhy** [BADBADBADBOY/pytorchOCR#64]
https://github.com/BADBADBADBOY/pytorchOCR/blob/efae5454651e96794dd7a460bd305dc9ccd95359/ptocr/model/backbone/det_mobilev3.py#L40
如果是这样的话，那这个就是空间注意力了，不是通道注意力，这样的计算量会更大，效果更好吧，作者是对比了两者，还是这边是失误？

**Comment by BADBADBADBOY** [comment]
> https://github.com/BADBADBADBOY/pytorchOCR/blob/efae5454651e96794dd7a460bd305dc9ccd95359/ptocr/model/backbone/det_mobilev3.py#L40
> 
> 
> 如果是这样的话，那这个就是空间注意力了，不是通道注意力，这样的计算量会更大，效果更好吧，作者是对比了两者，还是这边是失误？

这里就是这样设计的 ，没有进行通道注意
