### ISSUE TITLE
about mobilev3   abd rec _mibilnetv3

### ISSUE THREAD

**Issue by cqray1990** [BADBADBADBOY/pytorchOCR#67]
mobilev3 和mobilev3_bd哪个原版的？怎么有两个版本
后面为什么还要加个conv2

**Comment by fxwfzsxyq** [comment]
> mobilev3 和mobilev3_bd哪个原版的？怎么有两个版本 后面为什么还要加个conv2

_bd 是百度paddleocr的mv3
