### ISSUE TITLE
DBNet加类别分支部分的损失函数这里gt_score = gt_score - 1 这里的-1是什么意思，另外为什么要设置ignore_index=-1

### ISSUE THREAD

**Issue by liulei199409** [BADBADBADBOY/pytorchOCR#68]
gt_score = gt_score - 1
这里的-1是什么意思，另外为什么要设置ignore_index=-1

**Comment by BADBADBADBOY** [comment]
> gt_score = gt_score - 1 这里的-1是什么意思，另外为什么要设置ignore_index=-1

gt_score 里的0类是非文字的背景类，文字类别是从1开始的，所以输入计算分类loss要把这个减1，ignore_index=-1也是指计算loss的时，-1的这个不参与，因为0-1=-1

**Comment by liulei199409** [comment]
您好，在哪里设置的0类是非文字的背景类
