### ISSUE TITLE
STN训练

### ISSUE THREAD

**Issue by dlml** [BADBADBADBOY/pytorchOCR#69]
我训练了一下带有stn的结构，最终loss不收敛，是不是有什么问题呢？

**Comment by BADBADBADBOY** [comment]
> 我训练了一下带有stn的结构，最终loss不收敛，是不是有什么问题呢？

你说那个，这里没有stn的结构吧

**Comment by dlml** [comment]
是tps模块，我看你代码是把这部分注释掉了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月29日(周二) 上午9:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BADBADBADBOY/pytorchOCR] STN训练 (Issue #69)




  
我训练了一下带有stn的结构，最终loss不收敛，是不是有什么问题呢？
  
你说那个，这里没有stn的结构吧
