### ISSUE TITLE
crnn有训好的模型吗

### ISSUE THREAD

**Issue by Salight** [BADBADBADBOY/pytorchOCR#7]
作者您好，我发现这个repo做的非常好，对我非常有帮助，感谢你的贡献。
我在没有找到你的crnn训好的模型，请问CRNN的model会release吗，想先做infer测试一下效果。
另外，群二维码已经过期，可以提供一个新的吗？谢谢！

**Comment by BADBADBADBOY** [comment]
> 作者您好，我发现这个repo做的非常好，对我非常有帮助，感谢你的贡献。
> 我在没有找到你的crnn训好的模型，请问CRNN的model会release吗，想先做infer测试一下效果。
> 另外，群二维码已经过期，可以提供一个新的吗？谢谢！

最近比较忙，可能过段时间会更新

**Comment by BADBADBADBOY** [comment]
> 作者您好，我发现这个repo做的非常好，对我非常有帮助，感谢你的贡献。
> 我在没有找到你的crnn训好的模型，请问CRNN的model会release吗，想先做infer测试一下效果。
> 另外，群二维码已经过期，可以提供一个新的吗？谢谢！

fxwfzsxyq 你直接加我微信，我拉你进去
