### ISSUE TITLE
训练模型时报错

### ISSUE THREAD

**Issue by lixiangMindSpore** [BADBADBADBOY/pytorchOCR#74]
![image](https://user-images.githubusercontent.com/78945582/174771447-00fd7d33-8d71-4cdd-934b-e4db6d9ff139.png)

**Comment by lixiangMindSpore** [comment]
已解决，将det_DB_mobilev3.yaml里面的restore改成false

**Comment by cqray1990** [comment]
> 已解决，将det_DB_mobilev3.yaml里面的restore改成false

@lixiangMindSpore 
请问你训练icdar 数据能收敛？还是Acc一直为0.5
