### ISSUE TITLE
关于rec_infer.py中有一个模块不存在，请问这个包是用来做啥的？

### ISSUE THREAD

**Issue by sctcof** [BADBADBADBOY/pytorchOCR#77]
<img width="1264" alt="截屏2022-08-16 08 36 50" src="https://user-images.githubusercontent.com/30295895/184759183-c8481271-d441-48dd-a744-8a071ac33031.png">

**Comment by fxwfzsxyq** [comment]
> <img alt="截屏2022-08-16 08 36 50" width="1264" src="https://user-images.githubusercontent.com/30295895/184759183-c8481271-d441-48dd-a744-8a071ac33031.png">

![image](https://user-images.githubusercontent.com/18416103/184784655-e82b59cd-4c06-4d05-9e15-6a2e5e071d74.png)
计算这些数据准确率用的
