### ISSUE TITLE
项目很好，就是训练的模型不行，用起来不行给人一种错觉

### ISSUE THREAD

**Issue by futureflsl** [BADBADBADBOY/pytorchOCR#78]
同一张图片在paddleocr最轻量级模型比你的大模型效果都好，看了下你用的数据集少了。建议用和paddleocr一样数据集训练这样比较才能明显，而且你训练的模型只能测试用，很有限制。如果要是换大数据集应该就会好很大，不然初学者下载下来测试效果就直接放弃你这个项目，其实这个项目很不错。就是第一次体验检测效果不行。

**Comment by BADBADBADBOY** [comment]
> 同一张图片在paddleocr最轻量级模型比你的大模型效果都好，看了下你用的数据集少了。建议用和paddleocr一样数据集训练这样比较才能明显，而且你训练的模型只能测试用，很有限制。如果要是换大数据集应该就会好很大，不然初学者下载下来测试效果就直接放弃你这个项目，其实这个项目很不错。就是第一次体验检测效果不行。

感谢建议  我都好久更新了 当初做这个项目只是想熟悉下一些算法，初学者还是建议paddleOCR 文档详细 现在基本上可读性和torch差不多了
