### ISSUE TITLE
中文检测效果较好，是否用了中文数据集进行训练

### ISSUE THREAD

**Issue by leidahhh** [BADBADBADBOY/pytorchOCR#79]
作者您好，看到你放的图片当中，有中文数据集测试的效果，检测效果看起来很不错，请问是有利用中文数据集进行训练吗，另外针对中文识别的效果怎么样呢？

**Comment by BADBADBADBOY** [comment]
是的，用了一些公开数据集，算法都是类似的 性能基本正常把
