### ISSUE TITLE
hello, can you provide icdar2015 dict.txt？

### ISSUE THREAD

**Issue by CC-todo** [BADBADBADBOY/pytorchOCR#8]
index = self.dict[text[i][j]]
KeyError: 'J'

When I run rec_train.py I get the above error

**Comment by fxwfzsxyq** [comment]
> ```
> index = self.dict[text[i][j]]
> ```
> 
> KeyError: 'J'
> 
> When I run rec_train.py I get the above error

I think you should learn how to make label. Today I will update a function to generate these files

**Comment by BADBADBADBOY** [comment]
> > ```
> > index = self.dict[text[i][j]]
> > ```
> > 
> > 
> > KeyError: 'J'
> > When I run rec_train.py I get the above error
> 
> I think you should learn how to make label. Today I will update a function to generate these files

you can get key.txt by https://github.com/BADBADBADBOY/pytorchOCR/blob/master/script/get_key_label.py
