### ISSUE TITLE
DB二分类和多分类在计算评估指标时有什么区别？

### ISSUE THREAD

**Issue by Letdreamfly** [BADBADBADBOY/pytorchOCR#81]

**Comment by Letdreamfly** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/48435550/209264662-bcd70eee-c856-4395-9305-0d60ae2548ac.png">
我感觉这里并没有把DB多分类与DB二分类的评测区分开来？

**Comment by BADBADBADBOY** [comment]
> <img alt="image" width="886" src="https://user-images.githubusercontent.com/48435550/209264662-bcd70eee-c856-4395-9305-0d60ae2548ac.png">
> 
> 我感觉这里并没有把DB多分类与DB二分类的评测区分开来？

这里没有实现多分类的评测，这里只给了一般的基于分割类文本检测算法的评测

**Comment by BADBADBADBOY** [comment]
对于多分类的我没有做量化的评测 这里只是提供一种基于DB多分类的思路
