### ISSUE TITLE
torch2trt==0.0.3

### ISSUE THREAD

**Issue by Yangfan-study** [BADBADBADBOY/pytorchOCR#9]
pip install torch2trt==0.0.3
ERROR: Could not find a version that satisfies the requirement torch2trt==0.0.3 (from versions: none)
ERROR: No matching distribution found for torch2trt==0.0.3

还有能更新一下二维码吗，谢谢

**Comment by BADBADBADBOY** [comment]
> pip install torch2trt==0.0.3
> ERROR: Could not find a version that satisfies the requirement torch2trt==0.0.3 (from versions: none)
> ERROR: No matching distribution found for torch2trt==0.0.3
> 
> 还有能更新一下二维码吗，谢谢

换一下pip 源 ，加我微信，我拉你进去

**Comment by BADBADBADBOY** [comment]
> pip install torch2trt==0.0.3
> ERROR: Could not find a version that satisfies the requirement torch2trt==0.0.3 (from versions: none)
> ERROR: No matching distribution found for torch2trt==0.0.3
> 
> 还有能更新一下二维码吗，谢谢

fxwfzsxyq
